/**
 * Copyright (2018, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.isdream.chameleon.vm.aliyun.adapters;

import com.aliyuncs.auth.AlibabaCloudCredentials;
import com.aliyuncs.auth.AlibabaCloudCredentialsProvider;
import com.aliyuncs.profile.IClientProfile;

/**
 * generated by 
 * 
 * @author wuheng@otcaix.iscas.ac.cn
 *
 * 2018年2月19日
 */
public class DefaultAcsClient extends com.aliyuncs.DefaultAcsClient {

	public DefaultAcsClient(IClientProfile profile) {
		super(profile);
	}

	public DefaultAcsClient() {
		super();
	}

	public DefaultAcsClient(IClientProfile profile, AlibabaCloudCredentials credentials) {
		super(profile, credentials);
	}

	public DefaultAcsClient(IClientProfile profile, AlibabaCloudCredentialsProvider credentialsProvider) {
		super(profile, credentialsProvider);
	}

	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest createModifySecurityGroupRuleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest createCreateForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest createJoinSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest createModifyImageSharePermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest createDescribeInstanceVncUrlRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest createReActivateInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipFillProductRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipFillProductRequest createEipFillProductRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipFillProductRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest createLeaveSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest createResizeDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest createDeleteSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest createCancelCopyImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest createReplaceSystemDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest createCancelAgreementRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest createDeletePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest createAttachClassicLinkVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest createCreateRouteEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest createDescribeImageSupportInstanceTypesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest createRevokeSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest createDeactivateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.SignAgreementRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.SignAgreementRequest createSignAgreementRequest() {
		return new com.aliyuncs.ecs.model.v20140526.SignAgreementRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest createDescribeUserBusinessBehaviorRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest createDeleteVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest createModifyDiskChargeTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest createDescribeRenewalPriceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest createDescribeRouteTablesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest createDescribeAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CopyImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CopyImageRequest createCopyImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CopyImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StopInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StopInstanceRequest createStopInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StopInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest createDescribeSpotPriceHistoryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest createDescribeClustersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest createModifyImageAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest createDescribeTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest createModifyRouterInterfaceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest createDeleteRecycleBinRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest createUnassociateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest createModifyPrepayInstanceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest createDescribeSecurityGroupReferencesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest createDescribeInvocationResultsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest createModifySnapshotAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest createCreateHpcClusterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest createDescribeInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest createDescribeTaskAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest createModifyInstanceVpcAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest createCreateVSwitchRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest createCreateVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest createDescribeDisksFullStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest createAllocateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest createAttachInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest createCreateAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest createDescribeZonesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest createDeleteVSwitchRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest createAuthorizeSecurityGroupEgressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest createTerminateVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest createDescribeSecurityGroupsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest createDescribeVirtualBorderRoutersForPhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest createCreateKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest createDescribeInstanceTypesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest createEipFillParamsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest createActivateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest createDescribeSecurityGroupAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest createDescribeIpRangesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest createDescribeClassicLinkInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest createDescribeImageSharePermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StopInvocationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StopInvocationRequest createStopInvocationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StopInvocationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest createDescribeRouterInterfacesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest createCreateSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest createCheckDiskEnableAutoSnapshotValidationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ResetDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ResetDiskRequest createResetDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ResetDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest createConvertNatPublicIpToEipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest createModifyNetworkInterfaceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest createDescribeInstanceAutoRenewAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest createDeleteRouteEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelTaskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelTaskRequest createCancelTaskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelTaskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest createAssociateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest createDescribeSnapshotsUsageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StartInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StartInstanceRequest createStartInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StartInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest createModifyForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest createCreateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest createDeleteForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest createModifyVirtualBorderRouterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest createDescribeVSwitchesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest createDetachInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest createCreateDeploymentSetRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest createRemoveBandwidthPackageIpsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest createBindIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest createDeleteDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest createDescribeAvailableResourceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest createEipNotifyPaidRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest createModifySecurityGroupEgressRuleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest createCreateNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest createDeleteDeploymentSetRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest createUnassociateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest createDescribeInstanceStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest createDescribeHpcClustersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest createDescribeTagKeysRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest createModifyVSwitchAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest createModifyHaVipAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateDiskRequest createCreateDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest createRecoverVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest createDeleteHpcClusterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest createModifyAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest createDescribeNetworkInterfacesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest createDescribeInstancePhysicalAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest createDeleteKeyPairsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest createEnablePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest createTerminatePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest createDescribeInstanceTypeFamiliesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest createDescribeRecycleBinRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest createDescribeIntranetAttributeKbRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest createModifyCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest createAttachNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest createDescribeCommandsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest createInvokeCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest createAddBandwidthPackageIpsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest createDescribeUserDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest createDescribeInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest createCreateInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ImportImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ImportImageRequest createImportImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ImportImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest createDescribeDeploymentSetsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest createDescribeBandwidthPackagesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest createDeleteBandwidthPackageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteImageRequest createDeleteImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest createReleasePublicIpAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest createModifyInstanceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest createModifyAutoSnapshotPolicyExRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest createModifyPhysicalConnectionAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest createDescribeRegionsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest createDescribeResourcesModificationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest createDetachKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest createModifyInstanceVncPasswdRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest createDeleteAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest createModifyEipAddressAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest createDetachNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateImageRequest createCreateImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest createDescribeDeploymentSetTopologyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest createModifyHpcClusterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest createModifyRouterInterfaceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest createDescribeSnapshotsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest createModifyBandwidthPackageSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest createModifyInstanceAutoReleaseTimeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest createAllocatePublicIpAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest createDescribeInstancesFullStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest createCancelAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest createDescribeForwardTableEntriesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest createDescribeSnapshotMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest createCreatePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest createCheckAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest createDeleteCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest createModifyInstanceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest createDeleteNatGatewayRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest createConnectRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest createModifyInstanceChargeTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest createDeleteVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest createRebootInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ExportImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ExportImageRequest createExportImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ExportImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest createAuthorizeSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest createModifySecurityGroupPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest createCreateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest createRemoveTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest createDeleteInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest createDescribeInstanceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest createAddIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest createDescribeHaVipsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest createImportKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribePriceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribePriceRequest createDescribePriceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribePriceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest createDescribeNewProjectEipMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest createDescribeInstanceMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest createDeleteSnapshotRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachDiskRequest createAttachDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest createDetachClassicLinkVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest createUnbindIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest createDescribeEipAddressesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest createDescribeDiskMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest createDescribeNatGatewaysRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest createDescribeVirtualBorderRoutersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachDiskRequest createDetachDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RunInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RunInstancesRequest createRunInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RunInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest createDeleteHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest createModifySecurityGroupAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest createModifyInstanceAutoRenewAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest createDeleteRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest createModifyUserBusinessBehaviorRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest createApplyAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest createDescribeEipMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest createDescribeSnapshotLinksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest createCreateSnapshotRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest createDeleteNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest createDescribeResourceByTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest createDescribeSnapshotPackageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest createAssociateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest createRevokeSecurityGroupEgressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest createAttachKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateCommandRequest createCreateCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest createJoinResourceGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest createModifyDeploymentSetAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest createDescribeAutoSnapshotPolicyExRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest createDescribeRecommendInstanceTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest createModifyInstanceNetworkSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest createDescribeTasksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest createDescribeDisksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest createReInitDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest createCreateNatGatewayRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest createDescribeInstanceVncPasswdRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest createDescribeKeyPairsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest createModifyImageShareGroupPermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest createDescribeInvocationsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest createReleaseEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest createDescribeImagesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest createDescribePhysicalConnectionsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest createModifyDiskAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest createModifyVRouterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest createCancelPhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest createDescribeLimitationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVpcRequest createCreateVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest createRenewInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest createModifyIntranetBandwidthKbRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest createDescribeInstanceHistoryEventsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest createDescribeAccessPointsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest createDescribeBandwidthLimitationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest createModifyVpcAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest createDescribeVpcsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest createDescribeVRoutersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddTagsRequest createAddTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddTagsRequest();
	}
	   
}
