/**
 * Copyright (2018, ) Institute of Software, Chinese Academy of Sciences
 */
package com.github.isdream.chameleon.vm.aliyun.adapters;

import com.aliyuncs.auth.AlibabaCloudCredentials;
import com.aliyuncs.auth.AlibabaCloudCredentialsProvider;
import com.aliyuncs.profile.IClientProfile;

/**
 * generated by 
 * 
 * @author wuheng@otcaix.iscas.ac.cn
 *
 * 2018年2月19日
 */
public class DefaultAcsClient extends com.aliyuncs.DefaultAcsClient {

	public DefaultAcsClient(IClientProfile profile) {
		super(profile);
	}

	public DefaultAcsClient() {
		super();
	}

	public DefaultAcsClient(IClientProfile profile, AlibabaCloudCredentials credentials) {
		super(profile, credentials);
	}

	public DefaultAcsClient(IClientProfile profile, AlibabaCloudCredentialsProvider credentialsProvider) {
		super(profile, credentialsProvider);
	}

	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest proxyModifySecurityGroupRuleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupRuleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest proxyCreateForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest proxyJoinSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.JoinSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest proxyModifyImageSharePermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageSharePermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest proxyDescribeInstanceVncUrlRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncUrlRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest proxyReActivateInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReActivateInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipFillProductRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipFillProductRequest proxyEipFillProductRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipFillProductRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest proxyLeaveSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.LeaveSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest proxyResizeDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ResizeDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest proxyDeleteSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest proxyCancelCopyImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelCopyImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest proxyReplaceSystemDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReplaceSystemDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest proxyCancelAgreementRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelAgreementRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest proxyDeletePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeletePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest proxyAttachClassicLinkVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachClassicLinkVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest proxyCreateRouteEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateRouteEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest proxyDescribeImageSupportInstanceTypesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImageSupportInstanceTypesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest proxyRevokeSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest proxyDeactivateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeactivateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.SignAgreementRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.SignAgreementRequest proxySignAgreementRequest() {
		return new com.aliyuncs.ecs.model.v20140526.SignAgreementRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest proxyDescribeUserBusinessBehaviorRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeUserBusinessBehaviorRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest proxyDeleteVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest proxyModifyDiskChargeTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDiskChargeTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest proxyDescribeRenewalPriceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRenewalPriceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest proxyDescribeRouteTablesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRouteTablesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest proxyDescribeAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CopyImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CopyImageRequest proxyCopyImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CopyImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StopInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StopInstanceRequest proxyStopInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StopInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest proxyDescribeSpotPriceHistoryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSpotPriceHistoryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest proxyDescribeClustersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeClustersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest proxyModifyImageAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest proxyDescribeTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest proxyModifyRouterInterfaceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest proxyDeleteRecycleBinRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRecycleBinRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest proxyUnassociateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnassociateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest proxyModifyPrepayInstanceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyPrepayInstanceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest proxyDescribeSecurityGroupReferencesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupReferencesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest proxyDescribeInvocationResultsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInvocationResultsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest proxyModifySnapshotAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySnapshotAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest proxyCreateHpcClusterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateHpcClusterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest proxyDescribeInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest proxyDescribeTaskAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTaskAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest proxyModifyInstanceVpcAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceVpcAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest proxyCreateVSwitchRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVSwitchRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest proxyCreateVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest proxyDescribeDisksFullStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDisksFullStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest proxyAllocateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AllocateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest proxyAttachInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest proxyCreateAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest proxyDescribeZonesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeZonesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest proxyDeleteVSwitchRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVSwitchRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest proxyAuthorizeSecurityGroupEgressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupEgressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest proxyTerminateVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.TerminateVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest proxyDescribeSecurityGroupsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest proxyDescribeVirtualBorderRoutersForPhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersForPhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest proxyCreateKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest proxyDescribeInstanceTypesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest proxyEipFillParamsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipFillParamsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest proxyActivateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ActivateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest proxyDescribeSecurityGroupAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSecurityGroupAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest proxyDescribeIpRangesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeIpRangesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest proxyDescribeClassicLinkInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeClassicLinkInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest proxyDescribeImageSharePermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImageSharePermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StopInvocationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StopInvocationRequest proxyStopInvocationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StopInvocationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest proxyDescribeRouterInterfacesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRouterInterfacesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest proxyCreateSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest proxyCheckDiskEnableAutoSnapshotValidationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CheckDiskEnableAutoSnapshotValidationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ResetDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ResetDiskRequest proxyResetDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ResetDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest proxyConvertNatPublicIpToEipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ConvertNatPublicIpToEipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest proxyModifyNetworkInterfaceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyNetworkInterfaceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest proxyDescribeInstanceAutoRenewAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceAutoRenewAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest proxyDeleteRouteEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRouteEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelTaskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelTaskRequest proxyCancelTaskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelTaskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest proxyAssociateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AssociateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest proxyDescribeSnapshotsUsageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsUsageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.StartInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.StartInstanceRequest proxyStartInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.StartInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest proxyModifyForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest proxyCreateRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest proxyDeleteForwardEntryRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteForwardEntryRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest proxyModifyVirtualBorderRouterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVirtualBorderRouterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest proxyDescribeVSwitchesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVSwitchesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest proxyDetachInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest proxyCreateDeploymentSetRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateDeploymentSetRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest proxyRemoveBandwidthPackageIpsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RemoveBandwidthPackageIpsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest proxyBindIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.BindIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest proxyDeleteDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest proxyDescribeAvailableResourceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAvailableResourceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest proxyEipNotifyPaidRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EipNotifyPaidRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest proxyModifySecurityGroupEgressRuleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupEgressRuleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest proxyCreateNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest proxyDeleteDeploymentSetRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteDeploymentSetRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest proxyUnassociateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnassociateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest proxyDescribeInstanceStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest proxyDescribeHpcClustersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeHpcClustersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest proxyDescribeTagKeysRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTagKeysRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest proxyModifyVSwitchAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVSwitchAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest proxyModifyHaVipAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyHaVipAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateDiskRequest proxyCreateDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest proxyRecoverVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RecoverVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest proxyDeleteHpcClusterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteHpcClusterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest proxyModifyAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest proxyDescribeNetworkInterfacesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNetworkInterfacesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest proxyDescribeInstancePhysicalAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancePhysicalAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest proxyDeleteKeyPairsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteKeyPairsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest proxyEnablePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.EnablePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest proxyTerminatePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.TerminatePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest proxyDescribeInstanceTypeFamiliesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceTypeFamiliesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest proxyDescribeRecycleBinRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRecycleBinRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest proxyDescribeIntranetAttributeKbRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeIntranetAttributeKbRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest proxyModifyCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest proxyAttachNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest proxyDescribeCommandsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeCommandsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest proxyInvokeCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.InvokeCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest proxyAddBandwidthPackageIpsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddBandwidthPackageIpsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest proxyDescribeUserDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeUserDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest proxyDescribeInstanceRamRoleRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceRamRoleRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest proxyCreateInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ImportImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ImportImageRequest proxyImportImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ImportImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest proxyDescribeDeploymentSetsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest proxyDescribeBandwidthPackagesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeBandwidthPackagesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest proxyDeleteBandwidthPackageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteBandwidthPackageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteImageRequest proxyDeleteImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest proxyReleasePublicIpAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReleasePublicIpAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest proxyModifyInstanceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest proxyModifyAutoSnapshotPolicyExRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyAutoSnapshotPolicyExRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest proxyModifyPhysicalConnectionAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyPhysicalConnectionAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest proxyDescribeRegionsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRegionsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest proxyDescribeResourcesModificationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeResourcesModificationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest proxyDetachKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest proxyModifyInstanceVncPasswdRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceVncPasswdRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest proxyDeleteAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest proxyModifyEipAddressAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyEipAddressAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest proxyDetachNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateImageRequest proxyCreateImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest proxyDescribeDeploymentSetTopologyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDeploymentSetTopologyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest proxyModifyHpcClusterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyHpcClusterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest proxyModifyRouterInterfaceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyRouterInterfaceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest proxyDescribeSnapshotsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest proxyModifyBandwidthPackageSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyBandwidthPackageSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest proxyModifyInstanceAutoReleaseTimeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoReleaseTimeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest proxyAllocatePublicIpAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AllocatePublicIpAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest proxyDescribeInstancesFullStatusRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstancesFullStatusRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest proxyCancelAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest proxyDescribeForwardTableEntriesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeForwardTableEntriesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest proxyDescribeSnapshotMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest proxyCreatePhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreatePhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest proxyCheckAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CheckAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest proxyDeleteCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest proxyModifyInstanceSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest proxyDeleteNatGatewayRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteNatGatewayRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest proxyConnectRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ConnectRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest proxyModifyInstanceChargeTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceChargeTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest proxyDeleteVirtualBorderRouterRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteVirtualBorderRouterRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest proxyRebootInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RebootInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ExportImageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ExportImageRequest proxyExportImageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ExportImageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest proxyAuthorizeSecurityGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AuthorizeSecurityGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest proxyModifySecurityGroupPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest proxyCreateHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest proxyRemoveTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RemoveTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest proxyDeleteInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest proxyDescribeInstanceAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest proxyAddIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest proxyDescribeHaVipsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeHaVipsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest proxyImportKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ImportKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribePriceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribePriceRequest proxyDescribePriceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribePriceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest proxyDescribeNewProjectEipMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNewProjectEipMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest proxyDescribeInstanceMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest proxyDeleteSnapshotRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteSnapshotRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachDiskRequest proxyAttachDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest proxyDetachClassicLinkVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachClassicLinkVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest proxyUnbindIpRangeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.UnbindIpRangeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest proxyDescribeEipAddressesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeEipAddressesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest proxyDescribeDiskMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDiskMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest proxyDescribeNatGatewaysRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeNatGatewaysRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest proxyDescribeVirtualBorderRoutersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVirtualBorderRoutersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DetachDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DetachDiskRequest proxyDetachDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DetachDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RunInstancesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RunInstancesRequest proxyRunInstancesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RunInstancesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest proxyDeleteHaVipRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteHaVipRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest proxyModifySecurityGroupAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifySecurityGroupAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest proxyModifyInstanceAutoRenewAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceAutoRenewAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest proxyDeleteRouterInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteRouterInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest proxyModifyUserBusinessBehaviorRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyUserBusinessBehaviorRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest proxyApplyAutoSnapshotPolicyRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ApplyAutoSnapshotPolicyRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest proxyDescribeEipMonitorDataRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeEipMonitorDataRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest proxyDescribeSnapshotLinksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotLinksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest proxyCreateSnapshotRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateSnapshotRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest proxyDeleteNetworkInterfaceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DeleteNetworkInterfaceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest proxyDescribeResourceByTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeResourceByTagsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest proxyDescribeSnapshotPackageRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeSnapshotPackageRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest proxyAssociateEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AssociateEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest proxyRevokeSecurityGroupEgressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RevokeSecurityGroupEgressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest proxyAttachKeyPairRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AttachKeyPairRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateCommandRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateCommandRequest proxyCreateCommandRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateCommandRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest proxyJoinResourceGroupRequest() {
		return new com.aliyuncs.ecs.model.v20140526.JoinResourceGroupRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest proxyModifyDeploymentSetAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDeploymentSetAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest proxyDescribeAutoSnapshotPolicyExRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAutoSnapshotPolicyExRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest proxyDescribeRecommendInstanceTypeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeRecommendInstanceTypeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest proxyModifyInstanceNetworkSpecRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyInstanceNetworkSpecRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest proxyDescribeTasksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeTasksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest proxyDescribeDisksRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeDisksRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest proxyReInitDiskRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReInitDiskRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest proxyCreateNatGatewayRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateNatGatewayRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest proxyDescribeInstanceVncPasswdRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceVncPasswdRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest proxyDescribeKeyPairsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeKeyPairsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest proxyModifyImageShareGroupPermissionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyImageShareGroupPermissionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest proxyDescribeInvocationsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInvocationsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest proxyReleaseEipAddressRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ReleaseEipAddressRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest proxyDescribeImagesRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeImagesRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest proxyDescribePhysicalConnectionsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribePhysicalConnectionsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest proxyModifyDiskAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyDiskAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest proxyModifyVRouterAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVRouterAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest proxyCancelPhysicalConnectionRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CancelPhysicalConnectionRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest proxyDescribeLimitationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeLimitationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.CreateVpcRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.CreateVpcRequest proxyCreateVpcRequest() {
		return new com.aliyuncs.ecs.model.v20140526.CreateVpcRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest proxyRenewInstanceRequest() {
		return new com.aliyuncs.ecs.model.v20140526.RenewInstanceRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest proxyModifyIntranetBandwidthKbRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyIntranetBandwidthKbRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest proxyDescribeInstanceHistoryEventsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeInstanceHistoryEventsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest proxyDescribeAccessPointsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeAccessPointsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest proxyDescribeBandwidthLimitationRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeBandwidthLimitationRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest proxyModifyVpcAttributeRequest() {
		return new com.aliyuncs.ecs.model.v20140526.ModifyVpcAttributeRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest proxyDescribeVpcsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVpcsRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest proxyDescribeVRoutersRequest() {
		return new com.aliyuncs.ecs.model.v20140526.DescribeVRoutersRequest();
	}


	/**
	 * @return com.aliyuncs.ecs.model.v20140526.AddTagsRequest
	 */
	public com.aliyuncs.ecs.model.v20140526.AddTagsRequest proxyAddTagsRequest() {
		return new com.aliyuncs.ecs.model.v20140526.AddTagsRequest();
	}

}
