apiVersion: v1
kind: Template
labels:
  template: datavirt63-basic-s2i
  xpaas: 1.4.0
message: A new data service has been created in your project.  The username/password
  for accessing the service is ${TEIID_USERNAME}/${TEIID_PASSWORD}.  Please be sure
  to create the "${SERVICE_ACCOUNT_NAME}" service account and the secret named ${CONFIGURATION_NAME}
  containing the datasource configuration details required by the deployed VDB(s).
metadata:
  annotations:
    description: Application template for JBoss Data Virtualization 6.3 services built
      using S2I.
    iconClass: icon-jboss
    openshift.io/display-name: Red Hat JBoss Data Virtualization 6.3 (no SSL)
    tags: jdv,datavirt,jboss,xpaas
    version: 1.4.0
  creationTimestamp: 2017-12-27T03:03:28Z
  name: datavirt63-basic-s2i
  namespace: openshift
  resourceVersion: "982"
  selfLink: /oapi/v1/namespaces/openshift/templates/datavirt63-basic-s2i
  uid: 83548b2d-eab2-11e7-8531-0050569c0b78
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The data virtualization services.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: http
    - name: jdbc
      port: 31000
      targetPort: jdbc
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http (REST) service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    port:
      targetPort: http
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      images:
      - from:
          kind: ImageStreamTag
          name: jboss-datagrid65-client-openshift:1.0
          namespace: ${IMAGE_STREAM_NAMESPACE}
        paths:
        - destinationDir: ./${CONTEXT_DIR}/extensions/datagrid65
          sourcePath: /extensions/.
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        - name: CUSTOM_INSTALL_DIRECTORIES
          value: extensions/*
        - name: VDB_DIRS
          value: ${VDB_DIRS}
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jboss-datavirt63-openshift:1.2
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - imageChange: {}
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: jboss-datagrid65-client-openshift:1.0
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=${APPLICATION_NAME}
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JGROUPS_CLUSTER_PASSWORD
            value: ${JGROUPS_CLUSTER_PASSWORD}
          - name: AUTO_DEPLOY_EXPLODED
            value: ${AUTO_DEPLOY_EXPLODED}
          - name: TEIID_USERNAME
            value: ${TEIID_USERNAME}
          - name: TEIID_PASSWORD
            value: ${TEIID_PASSWORD}
          - name: MODESHAPE_USERNAME
            value: ${MODESHAPE_USERNAME}
          - name: MODESHAPE_PASSWORD
            value: ${MODESHAPE_PASSWORD}
          - name: ENV_FILES
            value: /etc/datavirt-environment/*
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 31000
            name: jdbc
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
          volumeMounts:
          - mountPath: /etc/datavirt-environment
            name: configuration
            readOnly: true
        serviceAccountName: ${SERVICE_ACCOUNT_NAME}
        terminationGracePeriodSeconds: 60
        volumes:
        - name: configuration
          secret:
            secretName: ${CONFIGURATION_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: datavirt-app
- description: The name of the secret containing configuration properties for the
    data sources.
  displayName: Configuration Secret Name
  name: CONFIGURATION_NAME
  required: true
  value: datavirt-app-config
- description: 'Specify a custom hostname for the http route.  Leave blank to use
    default hostname, e.g.: <service-name>-<project>.<default-domain-suffix>'
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/jboss-openshift/openshift-quickstarts
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: datavirt/dynamicvdb-datafederation/app
- description: The name of the service account to use for the deployment.  The service
    account should be configured to allow usage of the secret specified by CONFIGURATION_NAME.
  displayName: Service Account Name
  name: SERVICE_ACCOUNT_NAME
  required: true
  value: datavirt-service-account
- description: Username associated with Teiid data service.
  displayName: Teiid Username
  from: '[\a]{8}'
  generate: expression
  name: TEIID_USERNAME
  required: true
- description: Password for Teiid user.
  displayName: Teiid User Password
  from: '[\a\A]{8}[\d]{1}[\A]{1}'
  generate: expression
  name: TEIID_PASSWORD
  required: true
- description: Username associated with ModeShape.
  displayName: ModeShape Username
  from: '[\a]{8}'
  generate: expression
  name: MODESHAPE_USERNAME
  required: true
- description: Password for ModeShape user.
  displayName: ModeShape User Password
  from: '[\a\A]{8}[\d]{1}[\A]{1}'
  generate: expression
  name: MODESHAPE_PASSWORD
  required: true
- description: A secret string used to configure the GitHub webhook.
  displayName: Github Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: A secret string used to configure the Generic webhook.
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Password used by JGroups to authenticate nodes in the cluster.
  displayName: JGroups Cluster Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
- description: Controls whether exploded deployment content should be automatically
    deployed
  displayName: Deploy Exploded Archives
  name: AUTO_DEPLOY_EXPLODED
  value: "false"
- description: Comma delimited list of source directories containing VDBs for deployment
  displayName: VDB Deployment Directories
  name: VDB_DIRS
- description: Maven mirror to use for S2I builds
  displayName: Maven mirror URL
  name: MAVEN_MIRROR_URL
- description: List of directories from which archives will be copied into the deployment
    folder. If unspecified, all archives in /target will be copied.
  displayName: Artifact Directories
  name: ARTIFACT_DIR
