apiVersion: v1
kind: Template
labels:
  template: s2i-spring-boot-camel-teiid
metadata:
  annotations:
    description: Spring-Boot, Camel and JBoss Data Virtualization QuickStart. This
      example demonstrates how to connect Apache Camel to a remote JBoss Data Virtualization
      (or Teiid) Server using the JDBC protocol.
    iconClass: icon-jboss
    tags: quickstart,java,springboot,fis
    version: "2.0"
  creationTimestamp: 2017-12-27T03:03:30Z
  name: s2i-spring-boot-camel-teiid
  namespace: openshift
  resourceVersion: "1078"
  selfLink: /oapi/v1/namespaces/openshift/templates/s2i-spring-boot-camel-teiid
  uid: 843f1c0f-eab2-11e7-8531-0050569c0b78
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    resources: {}
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        - name: MAVEN_ARGS
          value: ${MAVEN_ARGS}
        - name: MAVEN_ARGS_APPEND
          value: ${MAVEN_ARGS_APPEND}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:${BUILDER_VERSION}
          namespace: ${IMAGE_STREAM_NAMESPACE}
        incremental: true
      type: Source
    triggers:
    - github:
        secret: ${BUILD_SECRET}
      type: GitHub
    - generic:
        secret: ${BUILD_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      component: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
          group: quickstarts
          project: ${APP_NAME}
          provider: s2i
          version: ${APP_VERSION}
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TEIID_SERVICE_NAME
            value: ${TEIID_SERVICE_NAME}
          - name: TEIID_PORT_NAME
            value: ${TEIID_PORT_NAME}
          - name: TEIID_USERNAME
            value: ${TEIID_USERNAME}
          - name: TEIID_PASSWORD
            value: ${TEIID_PASSWORD}
          image: library/${APP_NAME}:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 180
          name: ${APP_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: ${CPU_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
  status: {}
parameters:
- description: The name assigned to the application.
  displayName: Application Name
  name: APP_NAME
  required: true
  value: s2i-spring-boot-camel-teiid
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: GIT_REPO
  required: true
  value: https://github.com/fabric8-quickstarts/spring-boot-camel-teiid.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: GIT_REF
  value: spring-boot-camel-teiid-1.0.0.redhat-000053
- description: Set this to the name of the JDV Server. You may need to create an instance
    before.
  displayName: JDV Server Name
  name: TEIID_SERVICE_NAME
  required: true
  value: datavirt-app
- description: Set this to the name of the JDV port to use. Set this value if the
    JDV service contains multiple named ports.
  displayName: JDV Port Name
  name: TEIID_PORT_NAME
  value: jdbc
- description: The username used to authenticate with the JDV Server.
  displayName: JDV Server Username
  name: TEIID_USERNAME
  required: true
- description: The password used to authenticate with the JDV Server.
  displayName: JDV Server Password
  name: TEIID_PASSWORD
  required: true
- description: The version of the FIS S2I builder image to use.
  displayName: Builder version
  name: BUILDER_VERSION
  value: "2.0"
- description: The application version.
  displayName: Application Version
  name: APP_VERSION
  value: 1.0.0.redhat-000053
- description: Arguments passed to mvn in the build.
  displayName: Maven Arguments
  name: MAVEN_ARGS
  value: package -DskipTests -Dfabric8.skip -e -B
- description: Extra arguments passed to mvn, e.g. for multi-module builds.
  displayName: Extra Maven Arguments
  name: MAVEN_ARGS_APPEND
- description: Directory of the artifact to be built, e.g. for multi-module builds.
  displayName: Maven build directory
  name: ARTIFACT_DIR
- description: Namespace in which the Fuse ImageStreams are installed. These ImageStreams
    are normally installed in the openshift namespace. You should only need to modify
    this if you've installed the ImageStreams in a different namespace/project.
  displayName: Image Stream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: The secret needed to trigger a build.
  displayName: Git Build Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: BUILD_SECRET
- description: The amount of CPU to requests.
  displayName: CPU request
  name: CPU_REQUEST
  required: true
  value: "0.2"
- description: The amount of CPU the container is limited to use.
  displayName: CPU limit
  name: CPU_LIMIT
  required: true
  value: "1.0"
