apiVersion: v1
kind: Template
labels:
  template: datagrid65-https
  xpaas: 1.4.0
message: 'A new data grid service has been created in your project. It supports connector
  type(s) "${INFINISPAN_CONNECTORS}". Please be sure to create the "datagrid-service-account"
  service account and the following secrets: "${HTTPS_SECRET}" containing the ${HTTPS_KEYSTORE}
  file used for serving secure content; "${JGROUPS_ENCRYPT_SECRET}" containing the
  ${JGROUPS_ENCRYPT_KEYSTORE} file used for securing JGroups communications.'
metadata:
  annotations:
    description: Application template for JDG 6.5 applications.
    iconClass: icon-jboss
    openshift.io/display-name: Red Hat JBoss Data Grid 6.5 (Ephemeral with https)
    tags: datagrid,jboss,xpaas
    version: 1.4.0
  creationTimestamp: 2017-12-27T03:03:28Z
  name: datagrid65-https
  namespace: openshift
  resourceVersion: "977"
  selfLink: /oapi/v1/namespaces/openshift/templates/datagrid65-https
  uid: 834562d2-eab2-11e7-8531-0050569c0b78
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's HTTP port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's HTTPS port.
    labels:
      application: ${APPLICATION_NAME}
    name: secure-${APPLICATION_NAME}
  spec:
    ports:
    - port: 8443
      targetPort: 8443
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Memcached service for clustered applications.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-memcached
  spec:
    ports:
    - port: 11211
      targetPort: 11211
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Hot Rod service for clustered applications.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hotrod
  spec:
    ports:
    - port: 11333
      targetPort: 11333
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's HTTP service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's HTTPS service.
    labels:
      application: ${APPLICATION_NAME}
    name: secure-${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTPS}
    tls:
      termination: passthrough
    to:
      name: secure-${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: USERNAME
            value: ${USERNAME}
          - name: PASSWORD
            value: ${PASSWORD}
          - name: HTTPS_KEYSTORE_DIR
            value: /etc/datagrid-secret-volume
          - name: HTTPS_KEYSTORE
            value: ${HTTPS_KEYSTORE}
          - name: HTTPS_NAME
            value: ${HTTPS_NAME}
          - name: HTTPS_PASSWORD
            value: ${HTTPS_PASSWORD}
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=${APPLICATION_NAME}
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INFINISPAN_CONNECTORS
            value: ${INFINISPAN_CONNECTORS}
          - name: CACHE_NAMES
            value: ${CACHE_NAMES}
          - name: DATAVIRT_CACHE_NAMES
            value: ${DATAVIRT_CACHE_NAMES}
          - name: CACHE_TYPE_DEFAULT
            value: ${CACHE_TYPE_DEFAULT}
          - name: ENCRYPTION_REQUIRE_SSL_CLIENT_AUTH
            value: ${ENCRYPTION_REQUIRE_SSL_CLIENT_AUTH}
          - name: HOTROD_SERVICE_NAME
            value: ${APPLICATION_NAME}-hotrod
          - name: MEMCACHED_CACHE
            value: ${MEMCACHED_CACHE}
          - name: REST_SECURITY_DOMAIN
            value: ${REST_SECURITY_DOMAIN}
          - name: JGROUPS_ENCRYPT_SECRET
            value: ${JGROUPS_ENCRYPT_SECRET}
          - name: JGROUPS_ENCRYPT_KEYSTORE
            value: ${JGROUPS_ENCRYPT_KEYSTORE}
          - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
            value: /etc/jgroups-encrypt-secret-volume
          - name: JGROUPS_ENCRYPT_NAME
            value: ${JGROUPS_ENCRYPT_NAME}
          - name: JGROUPS_ENCRYPT_PASSWORD
            value: ${JGROUPS_ENCRYPT_PASSWORD}
          - name: JGROUPS_CLUSTER_PASSWORD
            value: ${JGROUPS_CLUSTER_PASSWORD}
          image: jboss-datagrid65-openshift
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/livenessProbe.sh
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          - containerPort: 11211
            name: memcached
            protocol: TCP
          - containerPort: 11222
            name: hotrod-internal
            protocol: TCP
          - containerPort: 11333
            name: hotrod
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/readinessProbe.sh
          volumeMounts:
          - mountPath: /etc/datagrid-secret-volume
            name: datagrid-keystore-volume
            readOnly: true
          - mountPath: /etc/jgroups-encrypt-secret-volume
            name: datagrid-jgroups-keystore-volume
            readOnly: true
        serviceAccountName: datagrid-service-account
        terminationGracePeriodSeconds: 60
        volumes:
        - name: datagrid-keystore-volume
          secret:
            secretName: ${HTTPS_SECRET}
        - name: datagrid-jgroups-keystore-volume
          secret:
            secretName: ${JGROUPS_ENCRYPT_SECRET}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: jboss-datagrid65-openshift:1.4
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: datagrid-app
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
- description: 'Custom hostname for https service route.  Leave blank for default
    hostname, e.g.: secure-<application-name>-<project>.<default-domain-suffix>'
  displayName: Custom https Route Hostname
  name: HOSTNAME_HTTPS
- description: User name for JDG user.
  displayName: Username
  name: USERNAME
- description: The password to access the JDG Caches. Must be different than username;
    must not be root, admin, or administrator; must contain at least 8 characters,
    1 alphabetic character(s), 1 digit(s), and 1 non-alphanumeric symbol(s). (optional)
  displayName: Password
  name: PASSWORD
- description: The name of the secret containing the keystore file
  displayName: Server Keystore Secret Name
  name: HTTPS_SECRET
  required: true
  value: datagrid-app-secret
- description: The name of the keystore file within the secret
  displayName: Server Keystore Filename
  name: HTTPS_KEYSTORE
  value: keystore.jks
- description: The name associated with the server certificate
  displayName: Server Certificate Name
  name: HTTPS_NAME
- description: The password for the keystore and certificate
  displayName: Server Keystore Password
  name: HTTPS_PASSWORD
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Comma-separated list of connector types that should be configured (defaults
    to 'memcached,hotrod,rest')
  displayName: Infinispan Connectors
  name: INFINISPAN_CONNECTORS
  value: hotrod,memcached,rest
- description: Comma-separated list of caches to configure.  By default, a distributed-cache,
    with a mode of SYNC will be configured for each entry.
  displayName: Cache Names
  name: CACHE_NAMES
- description: 'Comma-separated list of caches to configure for use by Red Hat JBoss
    Data Virtualization for materialization of views.  Three caches will be created
    for each named cache: <name>, <name>_staging and <name>_alias.'
  displayName: Datavirt Cache Names
  name: DATAVIRT_CACHE_NAMES
- description: Default cache type for all caches. If empty then distributed will be
    the default
  displayName: Default Cache Type
  name: CACHE_TYPE_DEFAULT
- displayName: Encryption Requires SSL Client Authentication?
  name: ENCRYPTION_REQUIRE_SSL_CLIENT_AUTH
- description: The name of the cache to expose through this memcached connector (defaults
    to 'default')
  displayName: Memcached Cache Name
  name: MEMCACHED_CACHE
  value: default
- description: The domain, declared in the security subsystem, that should be used
    to authenticate access to the REST endpoint
  displayName: REST Security Domain
  name: REST_SECURITY_DOMAIN
- description: The name of the secret containing the keystore file
  displayName: JGroups Secret Name
  name: JGROUPS_ENCRYPT_SECRET
  value: datagrid-app-secret
- description: The name of the keystore file within the secret
  displayName: JGroups Keystore Filename
  name: JGROUPS_ENCRYPT_KEYSTORE
  value: jgroups.jceks
- description: The name associated with the server certificate
  displayName: JGroups Certificate Name
  name: JGROUPS_ENCRYPT_NAME
- description: The password for the keystore and certificate
  displayName: JGroups Keystore Password
  name: JGROUPS_ENCRYPT_PASSWORD
- description: JGroups cluster password
  displayName: JGroups Cluster Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: JGROUPS_CLUSTER_PASSWORD
  required: true
