apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-example", "namespace": "development", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: development-pipeline
    template: application-template-development-pipeline
  name: development-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
        stage 'build'
        openshiftBuild(buildConfig: 'nodejs-example', showBuildLogs: 'true', namespace: 'development')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'nodejs-example', namespace: 'development')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
