apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-rc
  labels:
    app: busybox-rc
spec:
  replicas: 2
  selector:
    app: busybox-rc
  template:
    metadata:
      name: busybox-rc
      labels:
        app: busybox-rc
    spec:
      containers:
      - image: dcr.io:5000/busybox:latest
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox-rc
