apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    # deployment.kubernetes.io/revision: "1"
    platform: kubernetes1.8
    version: v1
  #creationTimestamp: 2018-01-03T03:50:06Z
  #generation: 1
  labels:
    application-real-name: tomcat-20180103115009290
    image-group-name: tomcat-43-v1-4dc75
    version-id: version-id-50000019
  name: tomcat-43-v1-4dc75
  namespace: development
  #resourceVersion: "220486"
  #selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/tomcat-43-v1-4dc75
  #uid: 2fb46da9-f039-11e7-9153-5254004dbd78
spec:
  replicas: 2
  selector:
    matchLabels:
      image-group-name: tomcat-43-v1-4dc75
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      #creationTimestamp: null
      labels:
        application-real-name: tomcat-20180103115009290
        image-group-name: tomcat-43-v1-4dc75
        version-id: version-id-50000019
    spec:
      containers:
      - image: dcr.io:5000/tomcat:latest
        imagePullPolicy: IfNotPresent
        name: tomcat1
        volumeMounts:
        - name: hostpath
          mountPath: /opt
        - name: emptydir
          mountPath: /etc
        env:
        - name: MESSAGE
          value: “hello world”
        - name: BAD
          value: “bad world”
        #command: 
        #- ls
        #args: 
        #- /
        ports:
        - containerPort: 8080
          # hostPort: 18080
        resources:
          limits:
            cpu: 800m
            memory: 2Gi
          requests:
            cpu: 400m
            memory: 512Mi
      - image: dci.io:5000/busybox:latest
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
      volumes:
      - name: hostpath
        hostPath:
          path: /opt
      - name: emptydir
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#status:
#  availableReplicas: 1
#  conditions:
#  - lastTransitionTime: 2018-01-03T03:50:06Z
#    lastUpdateTime: 2018-01-03T03:50:06Z
#    message: Deployment has minimum availability.
#    reason: MinimumReplicasAvailable
#    status: "True"
#    type: Available
#  observedGeneration: 1
#  readyReplicas: 1
#  replicas: 1
#  updatedReplicas: 1
