apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    application-real-name: demo-app-tomcat-20180307143430657
    image-group-name: demo-app-tomcat-43-v1-cf352
    version-id: version-id-50000013
  name: demo-app-tomcat-43-v1-cf352
  namespace: demo-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      image-group-name: demo-app-tomcat-43-v1-cf352
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application-real-name: demo-app-tomcat-20180307143430657
        image-group-name: demo-app-tomcat-43-v1-cf352
        version-id: version-id-50000013
    spec:
      containers:
      - env:
        - name: APPNAME
          value: demo-tomcat
        image: registry.example.com:5000/tomcat:latest
        imagePullPolicy: IfNotPresent
        name: demo-app-tomcat
        ports:
        - containerPort: 8080
          name: tomcat
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: config-volume2
          mountPath: /etc/config2
        - mountPath: "/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs"
          name: mypd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: tst-config
          items:
          - key: DASHBOARD.CONF.INI
            path: DASHBOARD.CONF.INI
          - key: REPLICAS
            path: REPLICAS
      - name: config-volume2
        configMap:
          name: tst-config
          items:
          - key: REPLICAS
            path: REPLICAS
      - name: mypd
        persistentVolumeClaim:
            claimName: weblogiclogs