apiVersion: v1
kind: Service
metadata:
  name: busybox-ss
  labels:
    app: busybox-ss
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: busybox-ss
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: busybox-ss
spec:
  serviceName: "busybox-ss"
  replicas: 2
  template:
    metadata:
      name: busybox-ss
      labels:
        app: busybox-ss
    spec:
      containers:
      - image: dcr.io:5000/busybox:latest
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox-ss
