apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - image: dcr.io:5000/busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-pod
