apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: wuheng
  labels:
    app: busybox-deployment
    version: 20180109
spec:
  replicas: 3
  template:
    metadata:
      name: busybox-deployment
      labels:
        app: busybox-deployment
        version: 20180109
    spec:
      containers:
      - image: dcr.io:5000/busybox:latest
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox-deployment
