apiVersion: v1
kind: Template
metadata:
  annotations:
    description: 3scale API Gateway
    iconClass: icon-load-balancer
    tags: api,gateway,3scale
  creationTimestamp: 2017-12-27T03:03:25Z
  name: 3scale-gateway
  namespace: openshift
  resourceVersion: "905"
  selfLink: /oapi/v1/namespaces/openshift/templates/3scale-gateway
  uid: 816229dd-eab2-11e7-8531-0050569c0b78
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APICAST_NAME}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${APICAST_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: ${APICAST_NAME}
      spec:
        containers:
        - env:
          - name: THREESCALE_PORTAL_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: password
                name: ${CONFIGURATION_URL_SECRET}
          - name: THREESCALE_CONFIG_FILE
            value: ${CONFIGURATION_FILE_PATH}
          - name: THREESCALE_DEPLOYMENT_ENV
            value: ${DEPLOYMENT_ENVIRONMENT}
          - name: RESOLVER
            value: ${RESOLVER}
          - name: APICAST_SERVICES
            value: ${SERVICES_LIST}
          - name: APICAST_CONFIGURATION_LOADER
            value: ${CONFIGURATION_LOADER}
          - name: APICAST_LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: APICAST_PATH_ROUTING_ENABLED
            value: ${PATH_ROUTING}
          - name: APICAST_RESPONSE_CODES
            value: ${RESPONSE_CODES}
          - name: APICAST_CONFIGURATION_CACHE
            value: ${CONFIGURATION_CACHE}
          - name: REDIS_URL
            value: ${REDIS_URL}
          - name: APICAST_MANAGEMENT_API
            value: ${MANAGEMENT_API}
          - name: OPENSSL_VERIFY
            value: ${OPENSSL_VERIFY}
          image: 3scale-amp20/apicast-gateway:1.0-3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /status/live
              port: management
            initialDelaySeconds: 10
            timeoutSeconds: 1
          name: ${APICAST_NAME}
          ports:
          - containerPort: 8080
            name: proxy
            protocol: TCP
          - containerPort: 8090
            name: management
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /status/ready
              port: management
            initialDelaySeconds: 15
            timeoutSeconds: 1
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APICAST_NAME}
  spec:
    ports:
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      deploymentconfig: ${APICAST_NAME}
parameters:
- description: AMP release tag.
  name: AMP_RELEASE
  required: true
  value: 2.0.0-CR2-redhat-1
- description: Name of the secret containing the THREESCALE_PORTAL_ENDPOINT with the
    access-token or provider key
  name: CONFIGURATION_URL_SECRET
  required: true
  value: apicast-configuration-url-secret
- description: Path to saved JSON file with configuration for the gateway. Has to
    be injected to the docker image as read only volume.
  name: CONFIGURATION_FILE_PATH
- description: Deployment environment. Can be sandbox or production.
  name: DEPLOYMENT_ENVIRONMENT
  required: true
  value: production
- description: Name for the 3scale API Gateway
  name: APICAST_NAME
  required: true
  value: apicast
- description: DNS Resolver for openresty, if empty it will be autodiscovered
  name: RESOLVER
- description: Subset of services to run. Use comma separated list of service ids
    (eg. 42,1337)
  name: SERVICES_LIST
- description: 'When to load configuration. If on gateway start or incoming request.
    Allowed values are: lazy, boot.'
  name: CONFIGURATION_LOADER
  value: boot
- description: 'Log level. One of the following: debug, info, notice, warn, error,
    crit, alert, or emerg.'
  name: LOG_LEVEL
- description: Enable path routing. Experimental feature.
  name: PATH_ROUTING
  value: "false"
- description: Enable logging response codes to 3scale.
  name: RESPONSE_CODES
  value: "false"
- description: For how long to cache the downloaded configuration in seconds. Can
    be left empty, 0 or greater than 60.
  name: CONFIGURATION_CACHE
- description: 'Redis URL. Required for OAuth2 integration. ex: redis://PASSWORD@127.0.0.1:6379/0'
  name: REDIS_URL
- description: Scope of the Management API. Can be disabled, status or debug. At least
    status required for health checks.
  name: MANAGEMENT_API
  value: status
- description: Turn on/off the OpenSSL peer verification. Can be set to true/false.
  name: OPENSSL_VERIFY
  required: true
  value: "false"
