apiVersion: v1
kind: Template
labels:
  template: gmas-s2i-gtja
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for building a war to tomcat with s2i
    iconClass: icon-jboss
    tags: tomcat,java,jboss,xpaas
    version: "1.0"
  creationTimestamp: null
  name: gmas-s2i-gtja
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: gmas-port
      nodePort: 31400
      port: 4007
      protocol: TCP
      targetPort: 4007
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    type: NodePort
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: /
      git:
        ref: master
        uri: http://10.189.99.14:3000/redhat/pubs2.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: WEB_URI
          value: ${WEB_URI}
#        - name: SVN_USER
#          value: ${SVN_USER}
#        - name: SVN_PWD
#          value: ${SVN_PWD}
#        - name: BUILD_CMD
#          value: ${BUILD_CMD}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: gmass2i:latest
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 4007
            name: http
            protocol: TCP
        terminationGracePeriodSeconds: 60
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: sample-app
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
- description: GIT  URI for application
  name: GIT_URI
  required: true
  value: http://10.189.99.14:3000/redhat/pubs2.git
#- description: Username for SVN.
#  name: SVN_USER
#  required: true
#  value: user1
#- description: Password for SVN.
#  name: SVN_PWD
#  required: true
#  value: Abcd1234
#- description: Build command for this project.
#  name: BUILD_CMD
#  required: true
#  value: ant
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: gmass2i
