apiVersion: v1
kind: Template
labels:
  template: harbormysql
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for MYSQL applications.
    iconClass: icon-mysql
    tags: harbormysql
    version: 1.2.0
  creationTimestamp: null
  name: harbormysql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
      router: inrouter
    name: ${APPLICATION_NAME}
  spec:
#    host: ${HOSTNAME_HTTP}
    host: ${APPLICATION_NAME}.inapps.jqpqa.c.saic-gm.net
    to:
      name: ${APPLICATION_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 3306
            name: http
            protocol: TCP
        nodeSelector:
          env: inrouter
    triggers:
    - type: ConfigChange

parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: harbormysql
#  generate: expression
#  from: "idm-[a-z]{2}[0-9]{1}[a-z]{3}"

#- description: 'Custom hostname for http service route.  Leave blank for default hostname,
#    e.g.: <application-name>-<project>.<default-domain-suffix>'
#  name: HOSTNAME_HTTP
#  required: true


- description: deploy image name
  name: IMAGE_NAME
  required: true
  value: registry.jqpreh.c.saic-gm.net/harbor/harbormysql
