apiVersion: v1
kind: Template
labels:
  template: idm
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for JWS applications.
    iconClass: icon-tomcat
    tags: tomcat,java,jboss,xpaas
    version: 1.2.0
  creationTimestamp: null
  name: idm
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
      router: exrouter
    name: ${APPLICATION_NAME}
  spec:
#    host: ${HOSTNAME_HTTP}
    host: ${APPLICATION_NAME}.exapps.jqpqa.c.saic-gm.net
    to:
      name: ${APPLICATION_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP

    triggers:
#    - type: ConfigChange
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        from:
          kind: "ImageStreamTag"
          name: "idm:latest"
          namespace: "idm"
        containerNames:
          - ${APPLICATION_NAME}



parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
#  value: jws-app
  generate: expression
  from: "idm-[a-z]{2}[0-9]{1}[a-z]{3}"

#- description: 'Custom hostname for http service route.  Leave blank for default hostname,
#    e.g.: <application-name>-<project>.<default-domain-suffix>'
#  name: HOSTNAME_HTTP
#  required: true


- description: deploy image name
  name: IMAGE_NAME
  required: true
  value: registry.jqpqa.c.saic-gm.net:5000/idm
