apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2016-12-06T09:33:18Z
  creationTimestamp: null
  generation: 3
  name: gmass2i
spec:
  tags:
  - annotations:
      description: Build and run NodeJS  applications
      iconClass: icon-tomcat
      sampleRepo: https://github.com/openshift/tomcat-ex.git
      supports: tomcat
      tags: builder,tomcat
      version: "latest"
    from:
      kind: DockerImage
      name:
    generation: 3
    importPolicy:
      insecure: true
    name: "latest"
  - annotations:
      description: Build and run tomcat applications
      iconClass: icon-tomcat
      sampleRepo: https://github.com/openshift/tomcat-ex.git
      supports: tomcat
      tags: builder,tomcat
    from:
      kind: DockerImage
      name: registry.example.com:5000/gmass2i:latest
    generation: 1
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
