apiVersion: v1
kind: Template
labels:
  template: tomcat7-template
  xpaas: 1.2.0
metadata:
  annotations:
    description: Application template for JWS applications.
    iconClass: icon-tomcat
    tags: tomcat,java,jboss,xpaas
    version: 1.2.0
  creationTimestamp: null
  name: tomcat7-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
      router: inrouter
    name: ${APPLICATION_NAME}
  spec:
#    host: ${HOSTNAME_HTTP}
    host: ${APPLICATION_NAME}.inapps.jqpqa.c.saic-gm.net
    to:
      name: ${APPLICATION_NAME}

    tls:
      termination: edge
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIGzDCCBbSgAwIBAgIKMKroEgABAAAOATANBgkqhkiG9w0BAQUFADCBrDEjMCEG
        CSqGSIb3DQEJARYUYWRtaW5Ac2hhbmdoYWlnbS5jb20xCzAJBgNVBAYTAkNOMREw
        DwYDVQQIEwhTaGFuZ2hhaTERMA8GA1UEBxMIU2hhbmdoYWkxIDAeBgNVBAoTF1No
        YW5naGFpIEdlbmVyYWwgTW90b3JzMSAwHgYDVQQLExdTaGFuZ2hhaSBHZW5lcmFs
        IE1vdG9yczEOMAwGA1UEAxMFU0dNQ0EwHhcNMTcxMTEzMDI0ODQxWhcNMjIxMDMw
        MDYyMjUyWjCBnzELMAkGA1UEBhMCQ04xETAPBgNVBAgTCFNoYW5naGFpMREwDwYD
        VQQHEwhTaGFuZ2hhaTEwMC4GA1UEChMnU0FJQyBHZW5lcmFsIE1vdG9ycyBDb3Jw
        b3JhdGlvbiBMaW1pdGVkMREwDwYDVQQLEwhJVCBEZXB0LjElMCMGA1UEAwwcKi5p
        bmFwcHMuanFwcWEuYy5zYWljLWdtLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEP
        ADCCAQoCggEBAMP5f705/UUCte7GbxVkjmhWA2tWD9kCQhPkMc4UwLIIK/uqiEYU
        TLKuR1mVeiEgxwJ/+10t655nmOereGsRRKkhlq7h7jnKElzvRzxRzwAWnnOw6qGx
        WDfFJhaNSKNSg9wSa0yFZsAV6QlGYXH1Z9hHTUrmaY6pkHoBF0/CzbMprD/KqIh/
        Xf85YHju8WNzgCvvg1ag7lKq51bBwSfSwxIkSV0nMGI2CifSKIicAk82QSySE1/Q
        CehRHqye/Ibrg9I6/aUX2FbIUq3wkfGSVctTNRVNn9FAhPPOU5GroFx+84su20Cw
        QgLhhkgoiyqe6JIJqpz4eh6jtxa6LLCo4ZsCAwEAAaOCAvkwggL1MB0GA1UdDgQW
        BBScYzRDiUph5Jvlp1JpftaeF7dkGTAfBgNVHSMEGDAWgBQw/E91cpRnrYwUQwHE
        klqU/dllWDCCAQIGA1UdHwSB+jCB9zCB9KCB8aCB7oaBs2xkYXA6Ly8vQ049U0dN
        Q0EoMSksQ049Y2FzZXJ2ZXIsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZp
        Y2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9c2hhbmdoYWlnbSxE
        Qz1jb20/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNz
        PWNSTERpc3RyaWJ1dGlvblBvaW50hjZodHRwOi8vY2FzZXJ2ZXIuc2hhbmdoYWln
        bS5jb20vQ2VydEVucm9sbC9TR01DQSgxKS5jcmwwggEYBggrBgEFBQcBAQSCAQow
        ggEGMIGnBggrBgEFBQcwAoaBmmxkYXA6Ly8vQ049U0dNQ0EsQ049QUlBLENOPVB1
        YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRp
        b24sREM9c2hhbmdoYWlnbSxEQz1jb20/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVj
        dENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwWgYIKwYBBQUHMAKGTmh0dHA6
        Ly9jYXNlcnZlci5zaGFuZ2hhaWdtLmNvbS9DZXJ0RW5yb2xsL2Nhc2VydmVyLnNo
        YW5naGFpZ20uY29tX1NHTUNBKDEpLmNydDALBgNVHQ8EBAMCBaAwPAYJKwYBBAGC
        NxUHBC8wLQYlKwYBBAGCNxUIscJcg+q2HIOhiTqEq9cMgsLsZhmC0pwJg4POQgIB
        ZAIBBDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwJwYJKwYBBAGCNxUK
        BBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDATANBgkqhkiG9w0BAQUFAAOCAQEA
        edFptd1Smg+HG5bO6fSpnYco5xpNANLXNEG0z4teM/F7MF6MMyftN4cu7TrKM6cs
        q8FOhrOWKxkSMNp+ieRxO+oOd4Z8r87BC/jcqI5TRVnwP2VQ+5R0C83di1LYlg7A
        +1jH5I9Yp2n9l6RMu1gvHxH1i2SMZb/2y3kcAKPVqYyG5d9/00GYMJKtHmWMQFoJ
        QU0XtxdirzMI4KL+VSsas37U0VaUJLEX7WYE/C7MHxOJkJOtO+uGA9J3NZSSlAOL
        vVWXEDx1oX+H7707hOrM39rIBLI/cV8lAZ7rJrGnaw3aDZILe3gToX8Ro2c2lm07
        jAHbmTx6MHA9wRMvuEnW2g==
        -----END CERTIFICATE-----

      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDD+X+9Of1FArXu
        xm8VZI5oVgNrVg/ZAkIT5DHOFMCyCCv7qohGFEyyrkdZlXohIMcCf/tdLeueZ5jn
        q3hrEUSpIZau4e45yhJc70c8Uc8AFp5zsOqhsVg3xSYWjUijUoPcEmtMhWbAFekJ
        RmFx9WfYR01K5mmOqZB6ARdPws2zKaw/yqiIf13/OWB47vFjc4Ar74NWoO5SqudW
        wcEn0sMSJEldJzBiNgon0iiInAJPNkEskhNf0AnoUR6snvyG64PSOv2lF9hWyFKt
        8JHxklXLUzUVTZ/RQITzzlORq6BcfvOLLttAsEIC4YZIKIsqnuiSCaqc+Hoeo7cW
        uiywqOGbAgMBAAECggEAN8+OOW2SW1zyQxXv/L+ubrhQMPlJehvShaevJ2lxl0IM
        hJeER7DwRtKrLzAKn/SduHCKPXceavZF7XQ/zv4T97bBGvzswzhxElZyixMhSH0o
        kvoHWBURcpCK0FFcJmcRdlMoi5pSMNIMk7+fcLza3hUwRexok2Bm7Nfys5xeyG7N
        aiA+IhCVt+nBFA5vCfKpIm8dCajXH5hoc672lFsJxc8x2HG8eSog0Tq3sPN3Amm6
        4jvE8y7DKr4q+65kYJPwaRJAZ9JZ5NoeCzhM3ev7reNPR8TGxuggPD3SZ5ryl9fg
        tXATCzeWdKsToKhZzkSXbXOz4X+L/bQkYsmikJxngQKBgQD6RJoTIFZZWTLhWBOL
        +pmQ0kEmMShTlBPAlSw/AHcmaeiErvwmgX6iqVj04MtVWThws+0hm5DPa+Nsnvlx
        nxsHvwLMh+XwurJwWjNCf6uQ4O8ZkDbbMspxKHKRWDau7u5X6FYRdDqbZkW0J9FU
        ySCNVQTJcO+j3EAANVd1eYTlGQKBgQDIdo7ypUwifP5c7DF938Z4cWEfB1MQ6u2C
        GumH0G32Z5bZUITzH7h5cZYoaaopNE7VBosrR4r2+0IN3zZGjtGtmrMRs+0UnCPj
        ykVDumvZhOeaU1Nb4taKroaugiJlX9CSrNJOvwlTDIMgpEqPR/LPvlkGMHyG2kEC
        1AaULkQ+0wKBgCkHRhsMmhtbvDOlNM8l7jcHwRZ5yJqrE/HmgrJxaRcrFatq5HuL
        jy8rhCHhGHSNg+s2FBIGZt8aWNZd2Zb+9nd2oQbW4KNueAJjRzQHqiC+P3R5aATX
        dsjGUMHzLEPRd9GBjVqfK1x+j77RKEg2ENgasAY2NZMvcG6YUBY6LcdBAoGAQkS3
        Ms2kIo6Rg+Rs5ACy2qQYiCpismgHRghhhQ1JHLjX7FUq7jhhQnxjOE7d+qsZGGEG
        ZrNK5CThjDZq+d5CwJIwejyxtit7zdTTGvWoq4q9CY5cMzcE12mkilHozvxiteo9
        x9xtV6/+NS86mq0dPsHdKiejMu05qpau6hN1ahMCgYBVZCB/bvgX8fzGRvt6+B91
        PjDfmfsaeTRwT/J/SNtRQEVkL4ANofMaYHtvkI296pmRYwNFC0J+IKNK6y+KnA/r
        5hY+1+JqmWvIkRHgFdu3eVZkjqU4Twx0iC23S/TLcQajPfw8QYai9QaNd87rjb25
        eWwe2eQYyRAFOY5DOAbzyw==
        -----END PRIVATE KEY-----

      caCertificate: |
        -----BEGIN CERTIFICATE-----
        MIIEczCCA1ugAwIBAgIQclgfBsXr5LdG8tNOs+rZszANBgkqhkiG9w0BAQUFADCB
        rDEjMCEGCSqGSIb3DQEJARYUYWRtaW5Ac2hhbmdoYWlnbS5jb20xCzAJBgNVBAYT
        AkNOMREwDwYDVQQIEwhTaGFuZ2hhaTERMA8GA1UEBxMIU2hhbmdoYWkxIDAeBgNV
        BAoTF1NoYW5naGFpIEdlbmVyYWwgTW90b3JzMSAwHgYDVQQLExdTaGFuZ2hhaSBH
        ZW5lcmFsIE1vdG9yczEOMAwGA1UEAxMFU0dNQ0EwHhcNMTIxMDMwMDYyMTU2WhcN
        MjIxMDMwMDYyMjUyWjCBrDEjMCEGCSqGSIb3DQEJARYUYWRtaW5Ac2hhbmdoYWln
        bS5jb20xCzAJBgNVBAYTAkNOMREwDwYDVQQIEwhTaGFuZ2hhaTERMA8GA1UEBxMI
        U2hhbmdoYWkxIDAeBgNVBAoTF1NoYW5naGFpIEdlbmVyYWwgTW90b3JzMSAwHgYD
        VQQLExdTaGFuZ2hhaSBHZW5lcmFsIE1vdG9yczEOMAwGA1UEAxMFU0dNQ0EwggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDd0mlZ9D9O2JXE0lPBw1/jTmTL
        Ajp8EWGGHpbE1NbzF6bw5SaLgw4iHLWYfyuMV5mZ/mU8KLD7t12/+yRfgy/MtDpr
        GEII0ozwyrXYqWWzqjK2vHo1n9Bw1BYaytUAfGAmF1hAr/wUcQ3TUpiZLQdOtQeE
        uXJIDBoG7uASL1yLNBdG2tbPpKwcb7BP1bWjojcHnoGHP4JuHuiMNERtngIJe3Z+
        edGamH8TO2IEQAsEDMFphD+xC1EQozslxr7GqG+S5oX5ZFpzU5IfurkEqmWwO+ux
        qq43cCBnLoxCBGqgVEGd/zlCopzyTPdNUY1eV5DNQ8P+P6HNWa0buU5HqFfzAgMB
        AAGjgY4wgYswEwYJKwYBBAGCNxQCBAYeBABDAEEwCwYDVR0PBAQDAgFGMA8GA1Ud
        EwEB/wQFMAMBAf8wHQYDVR0OBBYEFDD8T3VylGetjBRDAcSSWpT92WVYMBIGCSsG
        AQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYEFFvgkDn94956SHTxs/lU0/5i
        7zjWMA0GCSqGSIb3DQEBBQUAA4IBAQCxFNEb0SPd1sNNxAXjb6c7DTa0q3gYh2Oh
        bYt7X7XznLIvHc62OSH5i0ufDX97Y6taXKJ6npek31pTA2J5YbCTEpBxcRf5AiC9
        sTeMeFDoKgqihMGKsOjIo49+seZvjdfr6MfqZ2d5rtU+LwUkpCVptdsMZiySn0RG
        WQtHfsFi9kmVOCHHiIiQxeqmGHDR33RdUcbt4Ni3SyK0z0kfJEF6RCMhyEfTFp6/
        GRfuow2VEXTYR11zaavJ6B+hvhSRQNp5yqIoZ0Sk+Wa8JwxetQqeUbH0LVztXLjl
        TJjdSb3Il9ybr7XfzxhvqhQW4Gio8i6UOEotbXpCSI+TOepPvsIF
        -----END CERTIFICATE-----

      insecureEdgeTerminationPolicy: None
    wildcardPolicy: None



- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP

    triggers:
    - type: ConfigChange



parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
#  value: tomcat
  generate: expression
  from: "tomcat-[a-z]{2}[0-9]{1}[a-z]{3}"

#- description: 'Custom hostname for http service route.  Leave blank for default hostname,
#    e.g.: <application-name>-<project>.<default-domain-suffix>'
#  name: HOSTNAME_HTTP
#  required: true
#  value: tomcat.inapps.jqpqa.c.saic-gm.net



- description: deploy image name
  name: IMAGE_NAME
  required: true
  value: registry.jqpqa.c.saic-gm.net:5000/tomcat
