apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: busybox-rs
  labels:
    app: busybox-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-rs
  template:
    metadata:
      name: busybox-rs
      labels:
        app: busybox-rs
    spec:
      containers:
      - image: dcr.io:5000/busybox:latest
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox-rs
