apiVersion: v1
kind: Service
metadata:
  name: service-tomcat
  namespace: wuheng
  labels:
    name: label-tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31234
  selector:
    name: label-tomcat
    version: v1
